--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/xpocketmc/QuickCash
build-by-default: true
branches:
- stable
- main
- develop
projects:
  QuickCash:
    path: ""
    icon: "icon.png"
...
