name: QuickCash
version: 1.0.0
main: NurAzliYT\QuickCash\Main
api: 5.0.0
author: NurAzliYT
description: A simple economy plugin for PocketMine-MP

commands:
  mymoney:
    description: Shows your money
    permission: quickcash.command.mymoney
  mydebt:
    description: Shows your debt
    permission: quickcash.command.mydebt
  takedebt:
    description: Borrows money from the plugin
    permission: quickcash.command.takedebt
  returndebt:
    description: Returns money to the plugin
    permission: quickcash.command.returndebt
  topmoney:
    description: Shows server's top money
    permission: quickcash.command.topmoney
  moneysave:
    description: Saves data to your hardware
    permission: quickcash.command.moneysave
    permission-message: "You do not have permission to use this command"
  moneyload:
    description: Loads data from your hardware
    permission: quickcash.command.moneyload
    permission-message: "You do not have permission to use this command"
  setmoney:
    description: Sets a player's money
    permission: quickcash.command.setmoney
    permission-message: "You do not have permission to use this command"
  givemoney:
    description: Gives money to a player
    permission: quickcash.command.givemoney
    permission-message: "You do not have permission to use this command"
  takemoney:
    description: Takes money from a player
    permission: quickcash.command.takemoney
    permission-message: "You do not have permission to use this command"
  seemoney:
    description: Shows a player's money
    permission: quickcash.command.seemoney

permissions:
  quickcash.command.mymoney:
    default: true
  quickcash.command.mydebt:
    default: true
  quickcash.command.takedebt:
    default: true
  quickcash.command.returndebt:
    default: true
  quickcash.command.topmoney:
    default: true
  quickcash.command.moneysave:
    default: op
  quickcash.command.moneyload:
    default: op
  quickcash.command.setmoney:
    default: op
  quickcash.command.givemoney:
    default: op
  quickcash.command.takemoney:
    default: op
  quickcash.command.seemoney:
    default: true
